name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build Flutter APK and AAB
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'

    - name: Flutter Pre-cache
      run: flutter precache

    - name: Run Flutter Doctor
      run: flutter doctor -v

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Build AAB
      run: flutter build appbundle --release --no-shrink

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: flutter-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: flutter-aab
        path: build/app/outputs/bundle/release/app-release.aab
